//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devices()
        {
            this.ServiceOrders = new HashSet<ServiceOrders>();
        }
    
        public int DeviceID { get; set; }
        public int CustomerID { get; set; }
        public int DeviceTypeID { get; set; }
        public int ManufacturerID { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> YearOfManufacture { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> WarrantyExpiryDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual DeviceTypes DeviceTypes { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrders> ServiceOrders { get; set; }
    }
}
