//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceOrders()
        {
            this.UsedParts = new HashSet<UsedParts>();
        }
    
        public int OrderID { get; set; }
        public int DeviceID { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public int StatusID { get; set; }
        public string ProblemDescription { get; set; }
        public System.DateTime AcceptanceDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> FinalCost { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual RepairStatuses RepairStatuses { get; set; }
        public virtual Technicians Technicians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedParts> UsedParts { get; set; }
    }
}
