//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedParts
    {
        public int UsedPartID { get; set; }
        public int OrderID { get; set; }
        public int PartID { get; set; }
        public int Quantity { get; set; }
    
        public virtual ServiceOrders ServiceOrders { get; set; }
        public virtual SpareParts SpareParts { get; set; }
    }
}
